apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
spec:
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
