apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  ttlSecondsAfterFinished: 30 # after <duration> seconds job will be deleted
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        args:
        - /bin/sh
        - -c
        - date; echo Hello from the Kubernetes cluster
        # - exit 1 # backoffLimit FAIL
        # - while true; do date; echo Hello from the Kubernetes cluster; sleep 1; done # activeDeadlineSeconds FAIL
      restartPolicy: Never # best practice
 